#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use GVinaccia\DevCtl\InitCommand;
use GVinaccia\DevCtl\AddProject;

$application = new Application();
$application->add(new InitCommand);
$application->add(new AddProject);
$application->run();
